# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-09 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('note', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shakha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('time', models.TimeField(verbose_name='Time when shakha start')),
                ('days', models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday'), ('7', 'Daily')], default='7', max_length=1, verbose_name='Shakha Din')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Swaymsevak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20, verbose_name='first name')),
                ('mname', models.CharField(blank=True, max_length=20, null=True, verbose_name='middle name')),
                ('lname', models.CharField(max_length=20, verbose_name='Last name')),
                ('creted', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utsav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1', 'Varsh Pratipada'), ('2', 'Hindu Samrajya Diwas'), ('3', 'Gurupurnima'), ('4', 'Raksha Bandhan'), ('5', 'Vijyadashmi'), ('6', 'Makar Sankranti')], max_length=1, verbose_name='Utsav Name')),
                ('location', models.CharField(max_length=50, verbose_name='Where did')),
                ('time', models.DateTimeField(verbose_name='When did')),
                ('bal', models.PositiveSmallIntegerField()),
                ('tarun', models.PositiveSmallIntegerField()),
                ('shishu', models.PositiveSmallIntegerField()),
                ('any', models.PositiveSmallIntegerField()),
                ('cost', models.PositiveSmallIntegerField()),
                ('feedback', models.CharField(max_length=200, verbose_name='feedback/Notes about Utsav')),
                ('vakta', models.CharField(max_length=20)),
                ('shakha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shakha.Shakha')),
            ],
        ),
        migrations.CreateModel(
            name='Ghosh',
            fields=[
                ('name', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shakha.Swaymsevak')),
                ('ghosh', models.CharField(choices=[('v', 'Vamshi'), ('s', 'Shankh'), ('a', 'Anak')], default='v', max_length=1)),
                ('rachna', models.IntegerField(default=1, verbose_name='No. of Rachnas')),
            ],
        ),
        migrations.CreateModel(
            name='Sangh_Shikshan',
            fields=[
                ('name', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shakha.Swaymsevak')),
                ('shikshan', models.CharField(choices=[('p', 'Prathmik'), ('P', 'Pratham'), ('D', 'Dwitiya'), ('T', 'Tritiya')], max_length=1)),
                ('location', models.CharField(max_length=50, verbose_name='Where did')),
                ('year', models.IntegerField(default=2015)),
            ],
            options={
                'verbose_name': 'Sangh Shiksha',
            },
        ),
        migrations.CreateModel(
            name='Spersonal',
            fields=[
                ('name', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shakha.Swaymsevak')),
                ('contact', models.CharField(blank=True, max_length=10, null=True)),
                ('society', models.CharField(blank=True, max_length=50, null=True)),
                ('basti', models.CharField(blank=True, max_length=50, null=True)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('std', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='Job or School location')),
                ('emailid', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Id')),
                ('degree', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Personal Information Of Swaymsevak',
            },
        ),
        migrations.CreateModel(
            name='Sshakha',
            fields=[
                ('name', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shakha.Swaymsevak')),
                ('jimmedari', models.CharField(choices=[('0', 'Tat'), ('1', 'Pat'), ('2', 'Gatnayak'), ('3', 'Upgatnayak'), ('4', 'Vyastha Pramukh'), ('5', 'Geet Pramukh'), ('6', 'Khel Pramukh'), ('7', 'Gan Shikshak'), ('8', 'Prathna Pramukh'), ('9', 'Mukhy Shikshak'), ('10', 'Shakha Karyvah'), ('11', 'Palak')], default='1', max_length=2)),
                ('topi', models.BooleanField(choices=[(True, 'yes'), (False, 'no')], default=False)),
                ('shirt', models.BooleanField(choices=[(True, 'yes'), (False, 'no')], default=False)),
                ('pant', models.BooleanField(choices=[(True, 'yes'), (False, 'no')], default=False)),
                ('shocks', models.BooleanField(choices=[(True, 'yes'), (False, 'no')], default=False)),
                ('shoes', models.BooleanField(choices=[(True, 'yes'), (False, 'no')], default=False)),
                ('dand', models.BooleanField(choices=[(True, 'yes'), (False, 'no')], default=False)),
                ('ganvesh_complete', models.BooleanField(choices=[(True, 'yes'), (False, 'no')], default=False)),
                ('join_Year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Year When You Join ')),
                ('swaymsevak_type', models.CharField(blank=True, choices=[('1', 'Bal'), ('2', 'Tarun'), ('3', 'Shishu'), ('4', 'Praudh')], default='2', max_length=1, null=True)),
            ],
            options={
                'verbose_name': 'Shakha Related Information Of Swaymsevak',
            },
        ),
        migrations.AddField(
            model_name='swaymsevak',
            name='shakha',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='shakha.Shakha'),
        ),
        migrations.AddField(
            model_name='gat',
            name='gatnayak',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='shakha.Swaymsevak'),
        ),
        migrations.AddField(
            model_name='gat',
            name='shakha',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='shakha.Shakha'),
        ),
        migrations.AddField(
            model_name='sshakha',
            name='gat',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='shakha.Gat'),
        ),
    ]
