# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-30 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shakha', '0002_auto_20160711_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='sshakha',
            name='belt',
            field=models.BooleanField(choices=[(True, 'yes'), (False, 'no')], default=False),
        ),
    ]
