# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-17 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shakha', '0003_sshakha_belt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swaymsevak',
            name='lname',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Last name'),
        ),
    ]
