# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shakha', '0005_auto_20180317_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spersonal',
            name='basti',
            field=models.CharField(choices=[('1', 'Siddharth'), ('2', 'Satynagar'), ('3', 'Tanaji'), ('4', 'Krishna'), ('5', 'Ramjanki'), ('6', 'Umamaheswar'), ('7', 'Lalbahadur Shahstri'), ('8', 'Kajupada'), ('9', 'Netaji Nagar'), ('10', 'SunderBag Paschim'), ('11', 'SunderBag Purv')], default=1, max_length=2),
        ),
    ]
