# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-08-22 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shakha', '0007_auto_20180822_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sshakha',
            name='ganvesh_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ganvesh/6'),
        ),
    ]
